/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        ink: '#1a1a2e',
        paper: '#fbfaf7',
        brand: {
          50: '#eef4ff',
          100: '#d9e6ff',
          200: '#b3ccff',
          300: '#80a8ff',
          400: '#4d7fff',
          500: '#2b5cf0',
          600: '#1e44c4',
          700: '#183699',
          800: '#152a74',
          900: '#101f57',
        },
        // LearnFlow violet design system — additive, used by the new student
        // screens. Existing `ink`/`brand`/`paper` tokens above are untouched so
        // teacher screens render exactly as before.
        lf: {
          primary: '#7C3AED',
          primaryHover: '#6D28D9',
          primaryDeep: '#5B21B6',
          primaryLight: '#8B5CF6',
          indigo: '#6366F1',
          indigoDeep: '#4F46E5',
          ink: '#14121F',
          ink2: '#37344A',
          muted: '#6B6880',
          muted2: '#8A86A3',
          muted3: '#9C98B4',
          muted4: '#B4B0C4',
          line: '#EDEAF4',
          line2: '#E4E0EE',
          line3: '#E7E3F0',
          line4: '#F0EDF7',
          canvas: '#FAF8FB',
          canvas2: '#FBFAFC',
          canvas3: '#F5F3FA',
          canvas4: '#F7F5FB',
          purpleTint: '#FBF9FF',
          purpleTint2: '#F5F1FF',
          purpleTint3: '#EDE9FE',
          purpleTint4: '#E4DAFF',
          purpleTint5: '#EDE4FF',
          success: '#10B981',
          successDeep: '#047857',
          successTint: '#DCFCE7',
          successTint2: '#F2FCF7',
          successTint3: '#ECFDF5',
          successBorder: '#C7F0DE',
          danger: '#EF4444',
          dangerDeep: '#B91C1C',
          dangerDeep2: '#7F1D1D',
          dangerTint: '#FEE2E2',
          dangerTint2: '#FEF2F2',
          dangerTint3: '#FEF4F4',
          dangerBorder: '#FECACA',
          warning: '#F59E0B',
          warningDeep: '#B45309',
          warningTint: '#FFF4E5',
          warningBorder: '#FFE0B8',
          info: '#3B82F6',
          infoDeep: '#1D4ED8',
          infoTint: '#DBEAFE',
          teal: '#0891B2',
          pink: '#EC4899',
          pinkDeep: '#BE185D',
          pinkTint: '#FCE7F3',
          avatarPink: '#F472B6',
          disabled: '#DED9EA',
          locked: '#D5D0E2',
          locked2: '#CFC9DE',
          sidebarRule: '#26233A',
          tabActive: '#2A2540',
        },
      },
      fontFamily: {
        display: ['PlusJakartaSans_800ExtraBold', 'system-ui', 'sans-serif'],
        'display-bold': ['PlusJakartaSans_700Bold', 'system-ui', 'sans-serif'],
        'display-semibold': ['PlusJakartaSans_600SemiBold', 'system-ui', 'sans-serif'],
        'display-medium': ['PlusJakartaSans_500Medium', 'system-ui', 'sans-serif'],
        'display-regular': ['PlusJakartaSans_400Regular', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
