-- Staging/preview data for the "Additional Resources/Tasks" AI feature: one row per lesson
-- resource, generated by the generate-lesson-resources Edge Function. Teacher-only —
-- students only ever see content once a teacher explicitly attaches a card (which snapshots
-- the content into lesson_attached_tasks.content, see the next migration), never this table
-- directly, so regenerating doesn't retroactively change something already shown to students.
create type ai_resource_status as enum ('pending', 'ready', 'failed');

create table lesson_ai_resources (
  id uuid primary key default gen_random_uuid(),
  resource_id uuid not null unique references lesson_resources(id) on delete cascade,
  status ai_resource_status not null default 'pending',
  khan_academy jsonb,
  quizizz jsonb,
  mcqs jsonb,
  topic_summary text,
  error_message text,
  model text,
  generated_by uuid references profiles(id) on delete set null,
  generated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table lesson_ai_resources enable row level security;

create policy "lesson_ai_resources_teacher_read" on lesson_ai_resources for select
  using (
    exists (
      select 1 from lesson_resources r
      where r.id = lesson_ai_resources.resource_id
        and private.is_class_teacher(r.class_id)
    )
  );
-- Deliberately no insert/update/delete policy for any client role — only the Edge Function
-- (via the service role, which bypasses RLS) writes here.

-- Replaces the old placeholder 'quiz'/'assignment'/'project' picker cards. The old values are
-- left in the enum (Postgres can't drop enum values safely) but the app stops using them.
alter type lesson_task_kind add value 'khan_academy_video';
alter type lesson_task_kind add value 'quizizz_quiz';
alter type lesson_task_kind add value 'custom_mcqs';
